name: Metrics and Parallel Jobs

on:
  workflow_dispatch:

jobs:
  metrics_example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 16, 18]
        nizar: [1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print environment
        run: echo "Running on OS ${{ matrix.os }} with Node.js ${{ matrix.node }}"

  reference_external_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use third-party action
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Print Node.js version
        run: node -v

  reference_internal_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use internal action
        uses: ./.github/actions/logAction
        with:
          message: "This is a custom message"

  pr_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message: "Automated Review: Please check line X for improvements."